[phases.setup]
aptPkgs = [
    "libxcb1",
    "libxcb-xkb1", 
    "libxcb-render0",
    "libxcb-shm0",
    "libxcb-icccm4",
    "libxcb-image0",
    "libxcb-keysyms1",
    "libxcb-randr0",
    "libxcb-shape0",
    "libglib2.0-0",
    "libsm6",
    "libxext6",
    "libxrender1",
    "libgomp1",
    "libgl1",
    "ffmpeg"
]